"use client";
import localFont from "next/font/local";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import BasicLayout from "@/layouts/BasicLayout";
import React, {useCallback, useEffect} from "react";
import {Provider, useDispatch} from "react-redux";
import store, {AppDispatch} from "@/stores";
import "./globals.css";
import {getLoginUserUsingGet} from "@/api/userController";
import {setLoginUser} from "@/stores/loginUser";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
 });
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});


// 网页的标题描述
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };


const InitLayout: React.FC<Readonly<{
    children: React.ReactNode;
}>> = ({children}) => {

     const dispatch = useDispatch<AppDispatch>();

    /**
     * 全局初始化函数，有单次调用的代码
     */
    // useCallback 缓存函数  []中的变量不发生改变就不会出现渲染
    const doInitLoginUser = useCallback( async() => {
        const res = await getLoginUserUsingGet()
        if (res.data){
        //   更新全局用户状态
        } else {
            setTimeout(()=>{
                const test = {userName: "test", id: 1,userAvatar: "/assets/defaultUserAvatar.png"};
                dispatch(setLoginUser(test));
            },3000)
        }
    }, [])

    // 在next.js中开发环境useEffect会执行两次
    useEffect(() => {
        doInitLoginUser()
    }, []);

    return (
        children
    )
}


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
            <Provider store={store}>
                <InitLayout>
                    <BasicLayout>
                        {children}
                    </BasicLayout>
                </InitLayout>
            </Provider>
        </AntdRegistry>
        </body>
        </html>
    );
}
