"use client";
import localFont from "next/font/local";
import "./globals.css";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import BasicLayout from "@/layouts/BasicLayout";
import {useCallback, useEffect} from "react";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
 });
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});


// 网页的标题描述
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };


const InitLayout: React.FC<Readonly<{
    children: React.ReactNode;
}>> = ({children}) => {

    /**
     * 全局初始化函数，有单次调用的代码
     */
    // useCallback 缓存函数  []中的变量不发生改变就不会出现渲染
    const doInit = useCallback(() => {
        console.log("init")
    }, [])

    // 在next.js中开发环境useEffect会执行两次
    useEffect(() => {
        doInit()
    }, []);

    return (
        children
    )
}


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
            <InitLayout>
                <BasicLayout>
                    {children}
                </BasicLayout>
            </InitLayout>
        </AntdRegistry>
        </body>
        </html>
    );
}
